### ISSUE TITLE
This bot can´t join more servers as it has not been verified

### ISSUE THREAD

**Issue by JoToTheHannes** [Safemoon-Protocol/Discord-Bot#12] opened 2021-04-19 22:39 UTC
When I try to add the bot to my server the following error message appears:

**"This bot can´t join more servers as it has not been verified or is requesting gateway intents it has not been verified for. Ask the bot´s developer about https://disgd/bot-verification so you can add it to your server!"**

Screenshot is in german, sry.

![Screenshot 2021-04-20 003835](https://user-images.githubusercontent.com/49151667/115311951-c6e15f80-a170-11eb-97d0-83f4e3f2ec37.png)

**Comment by reecebenson** [comment] 2021-05-20 19:23
Duplicate of #7

**Closed as completed by reecebenson** 2021-05-20 19:23 UTC
